[git]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^removed", group = "removed" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
]
