[package]
name = "viewer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pollster = "0.3.0"
rive-rs = { path = "../../rive-rs", features = ["vello"] }
vello = { workspace = true }
wgpu = "0.17.0"
winit = "0.28.6"
